### ISSUE TITLE
Reference to Pyformlang

### ISSUE THREAD

**Issue by Aunsiels** [MBkkt/cppformlang#6]
Hi,

Great idea to port Pyformlang to C++. Can you refer to Pyformlang and give a link to its Github (https://github.com/Aunsiels/pyformlang) and readthedocs (https://pyformlang.readthedocs.io/) at the top of the Readme, please?

**Comment by MBkkt** [comment]
Yes, of course, sorry I didn't do it before

**Comment by Aunsiels** [comment]
Thanks!
